### ISSUE TITLE
`yarn build` throws build errors after merging in #56

### ISSUE THREAD

**Issue by jasonbosco** [typesense/docusaurus-theme-search-typesense#57]
## Description

Running `yarn build` throws build errors after merging in #56

## Steps to reproduce

```
$ yarn build
yarn run v1.22.19
$ tsc --build && node copyUntypedFiles.mjs && prettier --config .prettierrc --write "src/**/*.{js,ts,tsx,css}"
tsconfig.client.json:57:15 - error TS5110: Option 'module' must be set to 'NodeNext' when option 'moduleResolution' is set to 'NodeNext'.

57     "module": "esnext",
                 ~~~~~~~~


Found 1 error.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
````

## Metadata

Node 18, macOS

**Comment by jasonbosco** [comment]
cc: @tharropoulos

**Comment by tharropoulos** [comment]
This wasn't  a regression, this was present before! This will only throw when emitting with tsc and subsequently the compiler will fail because of the module / resolution mismatch looking at the [docusaurus](https://github.com/facebook/docusaurus/blob/f1272788a4d779a131f8f6e100d14d04cad1906f/tsconfig.base.json#L21) tsconfig, we should use `NodeNext` as the `module` setting. Will post up a PR for this
